//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPractica02
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Practica02PAMathiasEntities : DbContext
    {
        public Practica02PAMathiasEntities()
            : base("name=Practica02PAMathiasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Vehiculos> Vehiculos { get; set; }
        public virtual DbSet<Vendedores> Vendedores { get; set; }
        public virtual DbSet<Consultas> Consultas { get; set; }
    
        public virtual int VendedorPA(string cedula, string nombre, string correo, Nullable<bool> estado)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VendedorPA", cedulaParameter, nombreParameter, correoParameter, estadoParameter);
        }
    
        public virtual int InsertarVehiculo(string marca, string modelo, string color, Nullable<decimal> precio, Nullable<int> vendedorID)
        {
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var modeloParameter = modelo != null ?
                new ObjectParameter("Modelo", modelo) :
                new ObjectParameter("Modelo", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("Color", color) :
                new ObjectParameter("Color", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var vendedorIDParameter = vendedorID.HasValue ?
                new ObjectParameter("VendedorID", vendedorID) :
                new ObjectParameter("VendedorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarVehiculo", marcaParameter, modeloParameter, colorParameter, precioParameter, vendedorIDParameter);
        }
    
        public virtual ObjectResult<ConsultarVendedoresYVehiculos_Result> ConsultarVendedoresYVehiculos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarVendedoresYVehiculos_Result>("ConsultarVendedoresYVehiculos");
        }
    
        public virtual ObjectResult<ConsultarBD_Result> ConsultarBD(string cedula, string marca, string modelo, Nullable<decimal> precio)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var modeloParameter = modelo != null ?
                new ObjectParameter("Modelo", modelo) :
                new ObjectParameter("Modelo", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarBD_Result>("ConsultarBD", cedulaParameter, marcaParameter, modeloParameter, precioParameter);
        }
    }
}
